### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by halorium** [mr47/nuka-carousel-autoscroll#2]
I am trying to use your component as indicated in your documentation however I am getting the following error:

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `TimerComponent`.

**Comment by mr47** [comment]
@boobooninja can you provide your code for this case and what env you are using (babel/amd/?).
Thanks.

**Comment by halorium** [comment]
using babel, webpack
just using your example in your readme.

**Comment by mr47** [comment]
@boobooninja try new version, can help. If not what version of react and can you create a jsfiddle.
Thanks.

**Comment by atran** [comment]
+1, same issue here.

**Comment by atran** [comment]
Got around it by using:

```
  progressComponent: () => {
    return (<div />);
  },
```

**Comment by mr47** [comment]
@atran sorry for that a forget to mention that a progress component should always be.
I'll fix this. 
Thanks.

**Comment by mr47** [comment]
fixed
